game: 
	g++ game.cpp display.cpp music.cpp battle.cpp pokemon_data.cpp queue.cpp heap.c -lSDL2 -lSDL2_mixer -lmenu -lncurses -O0 -o pokemon
clean:
	rm -f *.o pokemon
debug: 
	g++ -g game.cpp display.cpp music.cpp battle.cpp pokemon_data.cpp queue.cpp heap.c -lSDL2 -lSDL2_mixer -lmenu -lncurses -O0 -o pokemon
